// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var Flatbuffer = Flatbuffer || {};

/**
 * @const
 * @namespace
 */
Flatbuffer.GroundTruth = Flatbuffer.GroundTruth || {};

/**
 * @enum
 */
Flatbuffer.GroundTruth.AssociationType = {
  ASSOCIATE: 0,
  PROPAGATE: 1,
  CREATE: 2,
  INVALID: 3
};

/**
 * @enum
 */
Flatbuffer.GroundTruth.TrackType = {
  INITIALIZING: 0,
  TRACKING: 1,
  DRIFTING: 2
};

/**
 * @enum
 */
Flatbuffer.GroundTruth.LaneType = {
  SOLID: 0,
  DASHED: 1,
  DOTTED: 2,
  UNKNOWN: 3
};

/**
 * @constructor
 */
Flatbuffer.GroundTruth.Vec3 = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Flatbuffer.GroundTruth.Vec3}
 */
Flatbuffer.GroundTruth.Vec3.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Vec3.prototype.x = function() {
  return this.bb.readFloat64(this.bb_pos);
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.Vec3.prototype.mutate_x = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 0);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Vec3.prototype.y = function() {
  return this.bb.readFloat64(this.bb_pos + 8);
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.Vec3.prototype.mutate_y = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Vec3.prototype.z = function() {
  return this.bb.readFloat64(this.bb_pos + 16);
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.Vec3.prototype.mutate_z = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 16);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 * @param {number} y
 * @param {number} z
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Vec3.createVec3 = function(builder, x, y, z) {
  builder.prep(8, 24);
  builder.writeFloat64(z);
  builder.writeFloat64(y);
  builder.writeFloat64(x);
  return builder.offset();
};

/**
 * @constructor
 */
Flatbuffer.GroundTruth.Vec2 = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Flatbuffer.GroundTruth.Vec2}
 */
Flatbuffer.GroundTruth.Vec2.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Vec2.prototype.x = function() {
  return this.bb.readFloat64(this.bb_pos);
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.Vec2.prototype.mutate_x = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 0);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Vec2.prototype.y = function() {
  return this.bb.readFloat64(this.bb_pos + 8);
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.Vec2.prototype.mutate_y = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 * @param {number} y
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Vec2.createVec2 = function(builder, x, y) {
  builder.prep(8, 16);
  builder.writeFloat64(y);
  builder.writeFloat64(x);
  return builder.offset();
};

/**
 * @constructor
 */
Flatbuffer.GroundTruth.Pose = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Flatbuffer.GroundTruth.Pose}
 */
Flatbuffer.GroundTruth.Pose.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Flatbuffer.GroundTruth.Pose=} obj
 * @returns {Flatbuffer.GroundTruth.Pose}
 */
Flatbuffer.GroundTruth.Pose.getRootAsPose = function(bb, obj) {
  return (obj || new Flatbuffer.GroundTruth.Pose).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {Flatbuffer.GroundTruth.Vec3=} obj
 * @returns {Flatbuffer.GroundTruth.Vec3|null}
 */
Flatbuffer.GroundTruth.Pose.prototype.pos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Flatbuffer.GroundTruth.Vec3).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {Flatbuffer.GroundTruth.Vec3=} obj
 * @returns {Flatbuffer.GroundTruth.Vec3|null}
 */
Flatbuffer.GroundTruth.Pose.prototype.vel = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new Flatbuffer.GroundTruth.Vec3).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {Flatbuffer.GroundTruth.Vec3=} obj
 * @returns {Flatbuffer.GroundTruth.Vec3|null}
 */
Flatbuffer.GroundTruth.Pose.prototype.acc = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new Flatbuffer.GroundTruth.Vec3).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {Flatbuffer.GroundTruth.Vec3=} obj
 * @returns {Flatbuffer.GroundTruth.Vec3|null}
 */
Flatbuffer.GroundTruth.Pose.prototype.orientation = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new Flatbuffer.GroundTruth.Vec3).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Pose.prototype.timestamp = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.Pose.prototype.mutate_timestamp = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 12);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Flatbuffer.GroundTruth.Pose.startPose = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 */
Flatbuffer.GroundTruth.Pose.addPos = function(builder, posOffset) {
  builder.addFieldStruct(0, posOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} velOffset
 */
Flatbuffer.GroundTruth.Pose.addVel = function(builder, velOffset) {
  builder.addFieldStruct(1, velOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} accOffset
 */
Flatbuffer.GroundTruth.Pose.addAcc = function(builder, accOffset) {
  builder.addFieldStruct(2, accOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} orientationOffset
 */
Flatbuffer.GroundTruth.Pose.addOrientation = function(builder, orientationOffset) {
  builder.addFieldStruct(3, orientationOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} timestamp
 */
Flatbuffer.GroundTruth.Pose.addTimestamp = function(builder, timestamp) {
  builder.addFieldFloat64(4, timestamp, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Pose.endPose = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Flatbuffer.GroundTruth.Poses = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Flatbuffer.GroundTruth.Poses}
 */
Flatbuffer.GroundTruth.Poses.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Flatbuffer.GroundTruth.Poses=} obj
 * @returns {Flatbuffer.GroundTruth.Poses}
 */
Flatbuffer.GroundTruth.Poses.getRootAsPoses = function(bb, obj) {
  return (obj || new Flatbuffer.GroundTruth.Poses).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {Flatbuffer.GroundTruth.Pose=} obj
 * @returns {Flatbuffer.GroundTruth.Pose}
 */
Flatbuffer.GroundTruth.Poses.prototype.poses = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Flatbuffer.GroundTruth.Pose).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Poses.prototype.posesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Flatbuffer.GroundTruth.Poses.startPoses = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posesOffset
 */
Flatbuffer.GroundTruth.Poses.addPoses = function(builder, posesOffset) {
  builder.addFieldOffset(0, posesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Poses.createPosesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Flatbuffer.GroundTruth.Poses.startPosesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Poses.endPoses = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Flatbuffer.GroundTruth.TrackingError = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Flatbuffer.GroundTruth.TrackingError}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Flatbuffer.GroundTruth.TrackingError=} obj
 * @returns {Flatbuffer.GroundTruth.TrackingError}
 */
Flatbuffer.GroundTruth.TrackingError.getRootAsTrackingError = function(bb, obj) {
  return (obj || new Flatbuffer.GroundTruth.TrackingError).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.XX = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.mutate_X_X = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 4);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.YY = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.mutate_Y_Y = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 6);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.speedSpeed = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.mutate_speed_speed = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.yawYaw = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.mutate_yaw_yaw = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 10);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.XY = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.mutate_X_Y = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 12);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.XSpeed = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.mutate_X_speed = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 14);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.XYaw = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.mutate_X_yaw = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 16);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.YSpeed = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.mutate_Y_speed = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 18);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.YYaw = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.mutate_Y_yaw = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 20);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.speedYaw = function() {
  var offset = this.bb.__offset(this.bb_pos, 22);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.TrackingError.prototype.mutate_speed_yaw = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 22);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Flatbuffer.GroundTruth.TrackingError.startTrackingError = function(builder) {
  builder.startObject(10);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} XX
 */
Flatbuffer.GroundTruth.TrackingError.addXX = function(builder, XX) {
  builder.addFieldFloat64(0, XX, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} YY
 */
Flatbuffer.GroundTruth.TrackingError.addYY = function(builder, YY) {
  builder.addFieldFloat64(1, YY, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} speedSpeed
 */
Flatbuffer.GroundTruth.TrackingError.addSpeedSpeed = function(builder, speedSpeed) {
  builder.addFieldFloat64(2, speedSpeed, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} yawYaw
 */
Flatbuffer.GroundTruth.TrackingError.addYawYaw = function(builder, yawYaw) {
  builder.addFieldFloat64(3, yawYaw, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} XY
 */
Flatbuffer.GroundTruth.TrackingError.addXY = function(builder, XY) {
  builder.addFieldFloat64(4, XY, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} XSpeed
 */
Flatbuffer.GroundTruth.TrackingError.addXSpeed = function(builder, XSpeed) {
  builder.addFieldFloat64(5, XSpeed, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} XYaw
 */
Flatbuffer.GroundTruth.TrackingError.addXYaw = function(builder, XYaw) {
  builder.addFieldFloat64(6, XYaw, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} YSpeed
 */
Flatbuffer.GroundTruth.TrackingError.addYSpeed = function(builder, YSpeed) {
  builder.addFieldFloat64(7, YSpeed, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} YYaw
 */
Flatbuffer.GroundTruth.TrackingError.addYYaw = function(builder, YYaw) {
  builder.addFieldFloat64(8, YYaw, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} speedYaw
 */
Flatbuffer.GroundTruth.TrackingError.addSpeedYaw = function(builder, speedYaw) {
  builder.addFieldFloat64(9, speedYaw, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.TrackingError.endTrackingError = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Flatbuffer.GroundTruth.State = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Flatbuffer.GroundTruth.State}
 */
Flatbuffer.GroundTruth.State.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Flatbuffer.GroundTruth.State=} obj
 * @returns {Flatbuffer.GroundTruth.State}
 */
Flatbuffer.GroundTruth.State.getRootAsState = function(bb, obj) {
  return (obj || new Flatbuffer.GroundTruth.State).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {Flatbuffer.GroundTruth.Vec3=} obj
 * @returns {Flatbuffer.GroundTruth.Vec3|null}
 */
Flatbuffer.GroundTruth.State.prototype.pos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Flatbuffer.GroundTruth.Vec3).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.State.prototype.timestamps = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.State.prototype.mutate_timestamps = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 6);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.State.prototype.speed = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.State.prototype.mutate_speed = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.State.prototype.yaw = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.State.prototype.mutate_yaw = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 10);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {number} index
 * @param {Flatbuffer.GroundTruth.Vec3=} obj
 * @returns {Flatbuffer.GroundTruth.Vec3}
 */
Flatbuffer.GroundTruth.State.prototype.bbox = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? (obj || new Flatbuffer.GroundTruth.Vec3).__init(this.bb.__vector(this.bb_pos + offset) + index * 24, this.bb) : null;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.State.prototype.bboxLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.State.prototype.height = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.State.prototype.mutate_height = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 14);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {Flatbuffer.GroundTruth.TrackingError=} obj
 * @returns {Flatbuffer.GroundTruth.TrackingError|null}
 */
Flatbuffer.GroundTruth.State.prototype.error = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? (obj || new Flatbuffer.GroundTruth.TrackingError).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {number} index
 * @returns {number}
 */
Flatbuffer.GroundTruth.State.prototype.detectionIds = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.readUint32(this.bb.__vector(this.bb_pos + offset) + index * 4) : 0;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.State.prototype.detectionIdsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint32Array}
 */
Flatbuffer.GroundTruth.State.prototype.detectionIdsArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? new Uint32Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @returns {Flatbuffer.GroundTruth.AssociationType}
 */
Flatbuffer.GroundTruth.State.prototype.associationType = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? /** @type {Flatbuffer.GroundTruth.AssociationType} */ (this.bb.readInt8(this.bb_pos + offset)) : Flatbuffer.GroundTruth.AssociationType.ASSOCIATE;
};

/**
 * @param {Flatbuffer.GroundTruth.AssociationType} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.State.prototype.mutate_associationType = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 20);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {Flatbuffer.GroundTruth.TrackType}
 */
Flatbuffer.GroundTruth.State.prototype.trackType = function() {
  var offset = this.bb.__offset(this.bb_pos, 22);
  return offset ? /** @type {Flatbuffer.GroundTruth.TrackType} */ (this.bb.readInt8(this.bb_pos + offset)) : Flatbuffer.GroundTruth.TrackType.INITIALIZING;
};

/**
 * @param {Flatbuffer.GroundTruth.TrackType} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.State.prototype.mutate_trackType = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 22);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {Flatbuffer.GroundTruth.Vec3=} obj
 * @returns {Flatbuffer.GroundTruth.Vec3|null}
 */
Flatbuffer.GroundTruth.State.prototype.egoPosition = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 24);
  return offset ? (obj || new Flatbuffer.GroundTruth.Vec3).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {Flatbuffer.GroundTruth.Vec3=} obj
 * @returns {Flatbuffer.GroundTruth.Vec3|null}
 */
Flatbuffer.GroundTruth.State.prototype.egoVelocity = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 26);
  return offset ? (obj || new Flatbuffer.GroundTruth.Vec3).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {Flatbuffer.GroundTruth.Vec3=} obj
 * @returns {Flatbuffer.GroundTruth.Vec3|null}
 */
Flatbuffer.GroundTruth.State.prototype.egoOrientation = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 28);
  return offset ? (obj || new Flatbuffer.GroundTruth.Vec3).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Flatbuffer.GroundTruth.State.startState = function(builder) {
  builder.startObject(13);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 */
Flatbuffer.GroundTruth.State.addPos = function(builder, posOffset) {
  builder.addFieldStruct(0, posOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} timestamps
 */
Flatbuffer.GroundTruth.State.addTimestamps = function(builder, timestamps) {
  builder.addFieldFloat64(1, timestamps, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} speed
 */
Flatbuffer.GroundTruth.State.addSpeed = function(builder, speed) {
  builder.addFieldFloat64(2, speed, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} yaw
 */
Flatbuffer.GroundTruth.State.addYaw = function(builder, yaw) {
  builder.addFieldFloat64(3, yaw, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} bboxOffset
 */
Flatbuffer.GroundTruth.State.addBbox = function(builder, bboxOffset) {
  builder.addFieldOffset(4, bboxOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Flatbuffer.GroundTruth.State.startBboxVector = function(builder, numElems) {
  builder.startVector(24, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} height
 */
Flatbuffer.GroundTruth.State.addHeight = function(builder, height) {
  builder.addFieldFloat64(5, height, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} errorOffset
 */
Flatbuffer.GroundTruth.State.addError = function(builder, errorOffset) {
  builder.addFieldOffset(6, errorOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} detectionIdsOffset
 */
Flatbuffer.GroundTruth.State.addDetectionIds = function(builder, detectionIdsOffset) {
  builder.addFieldOffset(7, detectionIdsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.State.createDetectionIdsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Flatbuffer.GroundTruth.State.startDetectionIdsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Flatbuffer.GroundTruth.AssociationType} associationType
 */
Flatbuffer.GroundTruth.State.addAssociationType = function(builder, associationType) {
  builder.addFieldInt8(8, associationType, Flatbuffer.GroundTruth.AssociationType.ASSOCIATE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Flatbuffer.GroundTruth.TrackType} trackType
 */
Flatbuffer.GroundTruth.State.addTrackType = function(builder, trackType) {
  builder.addFieldInt8(9, trackType, Flatbuffer.GroundTruth.TrackType.INITIALIZING);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} egoPositionOffset
 */
Flatbuffer.GroundTruth.State.addEgoPosition = function(builder, egoPositionOffset) {
  builder.addFieldStruct(10, egoPositionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} egoVelocityOffset
 */
Flatbuffer.GroundTruth.State.addEgoVelocity = function(builder, egoVelocityOffset) {
  builder.addFieldStruct(11, egoVelocityOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} egoOrientationOffset
 */
Flatbuffer.GroundTruth.State.addEgoOrientation = function(builder, egoOrientationOffset) {
  builder.addFieldStruct(12, egoOrientationOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.State.endState = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Flatbuffer.GroundTruth.Track = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Flatbuffer.GroundTruth.Track}
 */
Flatbuffer.GroundTruth.Track.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Flatbuffer.GroundTruth.Track=} obj
 * @returns {Flatbuffer.GroundTruth.Track}
 */
Flatbuffer.GroundTruth.Track.getRootAsTrack = function(bb, obj) {
  return (obj || new Flatbuffer.GroundTruth.Track).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {Flatbuffer.GroundTruth.State=} obj
 * @returns {Flatbuffer.GroundTruth.State}
 */
Flatbuffer.GroundTruth.Track.prototype.states = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Flatbuffer.GroundTruth.State).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Track.prototype.statesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Track.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.Track.prototype.mutate_id = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 6);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint32(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Flatbuffer.GroundTruth.Track.startTrack = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} statesOffset
 */
Flatbuffer.GroundTruth.Track.addStates = function(builder, statesOffset) {
  builder.addFieldOffset(0, statesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Track.createStatesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Flatbuffer.GroundTruth.Track.startStatesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
Flatbuffer.GroundTruth.Track.addId = function(builder, id) {
  builder.addFieldInt32(1, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Track.endTrack = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Flatbuffer.GroundTruth.Tracks = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Flatbuffer.GroundTruth.Tracks}
 */
Flatbuffer.GroundTruth.Tracks.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Flatbuffer.GroundTruth.Tracks=} obj
 * @returns {Flatbuffer.GroundTruth.Tracks}
 */
Flatbuffer.GroundTruth.Tracks.getRootAsTracks = function(bb, obj) {
  return (obj || new Flatbuffer.GroundTruth.Tracks).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {Flatbuffer.GroundTruth.Track=} obj
 * @returns {Flatbuffer.GroundTruth.Track}
 */
Flatbuffer.GroundTruth.Tracks.prototype.tracks = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Flatbuffer.GroundTruth.Track).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Tracks.prototype.tracksLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Flatbuffer.GroundTruth.Tracks.startTracks = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} tracksOffset
 */
Flatbuffer.GroundTruth.Tracks.addTracks = function(builder, tracksOffset) {
  builder.addFieldOffset(0, tracksOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Tracks.createTracksVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Flatbuffer.GroundTruth.Tracks.startTracksVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Tracks.endTracks = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Flatbuffer.GroundTruth.Detection = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Flatbuffer.GroundTruth.Detection}
 */
Flatbuffer.GroundTruth.Detection.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Flatbuffer.GroundTruth.Detection=} obj
 * @returns {Flatbuffer.GroundTruth.Detection}
 */
Flatbuffer.GroundTruth.Detection.getRootAsDetection = function(bb, obj) {
  return (obj || new Flatbuffer.GroundTruth.Detection).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Detection.prototype.timestamp = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.Detection.prototype.mutate_timestamp = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 4);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {Flatbuffer.GroundTruth.Vec3=} obj
 * @returns {Flatbuffer.GroundTruth.Vec3|null}
 */
Flatbuffer.GroundTruth.Detection.prototype.centroid = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new Flatbuffer.GroundTruth.Vec3).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Detection.prototype.heading = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.Detection.prototype.mutate_heading = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Detection.prototype.majorAxis = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.Detection.prototype.mutate_major_axis = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 10);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Detection.prototype.minorAxis = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.Detection.prototype.mutate_minor_axis = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 12);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Detection.prototype.height = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.Detection.prototype.mutate_height = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 14);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Detection.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.Detection.prototype.mutate_id = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 16);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint32(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Flatbuffer.GroundTruth.Detection.startDetection = function(builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} timestamp
 */
Flatbuffer.GroundTruth.Detection.addTimestamp = function(builder, timestamp) {
  builder.addFieldFloat64(0, timestamp, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} centroidOffset
 */
Flatbuffer.GroundTruth.Detection.addCentroid = function(builder, centroidOffset) {
  builder.addFieldStruct(1, centroidOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} heading
 */
Flatbuffer.GroundTruth.Detection.addHeading = function(builder, heading) {
  builder.addFieldFloat64(2, heading, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} majorAxis
 */
Flatbuffer.GroundTruth.Detection.addMajorAxis = function(builder, majorAxis) {
  builder.addFieldFloat64(3, majorAxis, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} minorAxis
 */
Flatbuffer.GroundTruth.Detection.addMinorAxis = function(builder, minorAxis) {
  builder.addFieldFloat64(4, minorAxis, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} height
 */
Flatbuffer.GroundTruth.Detection.addHeight = function(builder, height) {
  builder.addFieldFloat64(5, height, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
Flatbuffer.GroundTruth.Detection.addId = function(builder, id) {
  builder.addFieldInt32(6, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Detection.endDetection = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Flatbuffer.GroundTruth.Detections = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Flatbuffer.GroundTruth.Detections}
 */
Flatbuffer.GroundTruth.Detections.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Flatbuffer.GroundTruth.Detections=} obj
 * @returns {Flatbuffer.GroundTruth.Detections}
 */
Flatbuffer.GroundTruth.Detections.getRootAsDetections = function(bb, obj) {
  return (obj || new Flatbuffer.GroundTruth.Detections).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {Flatbuffer.GroundTruth.Detection=} obj
 * @returns {Flatbuffer.GroundTruth.Detection}
 */
Flatbuffer.GroundTruth.Detections.prototype.detections = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Flatbuffer.GroundTruth.Detection).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Detections.prototype.detectionsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Flatbuffer.GroundTruth.Detections.startDetections = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} detectionsOffset
 */
Flatbuffer.GroundTruth.Detections.addDetections = function(builder, detectionsOffset) {
  builder.addFieldOffset(0, detectionsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Detections.createDetectionsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Flatbuffer.GroundTruth.Detections.startDetectionsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Detections.endDetections = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Flatbuffer.GroundTruth.Lane = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Flatbuffer.GroundTruth.Lane}
 */
Flatbuffer.GroundTruth.Lane.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Flatbuffer.GroundTruth.Lane=} obj
 * @returns {Flatbuffer.GroundTruth.Lane}
 */
Flatbuffer.GroundTruth.Lane.getRootAsLane = function(bb, obj) {
  return (obj || new Flatbuffer.GroundTruth.Lane).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Lane.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.Lane.prototype.mutate_id = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 4);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint32(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {number} index
 * @returns {number}
 */
Flatbuffer.GroundTruth.Lane.prototype.timestamp = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readFloat64(this.bb.__vector(this.bb_pos + offset) + index * 8) : 0;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Lane.prototype.timestampLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Float64Array}
 */
Flatbuffer.GroundTruth.Lane.prototype.timestampArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? new Float64Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {number} index
 * @param {Flatbuffer.GroundTruth.Vec3=} obj
 * @returns {Flatbuffer.GroundTruth.Vec3}
 */
Flatbuffer.GroundTruth.Lane.prototype.left = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new Flatbuffer.GroundTruth.Vec3).__init(this.bb.__vector(this.bb_pos + offset) + index * 24, this.bb) : null;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Lane.prototype.leftLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {Flatbuffer.GroundTruth.Vec3=} obj
 * @returns {Flatbuffer.GroundTruth.Vec3}
 */
Flatbuffer.GroundTruth.Lane.prototype.right = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new Flatbuffer.GroundTruth.Vec3).__init(this.bb.__vector(this.bb_pos + offset) + index * 24, this.bb) : null;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Lane.prototype.rightLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {Flatbuffer.GroundTruth.Vec3=} obj
 * @returns {Flatbuffer.GroundTruth.Vec3}
 */
Flatbuffer.GroundTruth.Lane.prototype.spine = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? (obj || new Flatbuffer.GroundTruth.Vec3).__init(this.bb.__vector(this.bb_pos + offset) + index * 24, this.bb) : null;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Lane.prototype.spineLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @returns {Flatbuffer.GroundTruth.LaneType}
 */
Flatbuffer.GroundTruth.Lane.prototype.laneTypeLeft = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? /** @type {Flatbuffer.GroundTruth.LaneType} */ (this.bb.readInt8(this.bb.__vector(this.bb_pos + offset) + index)) : /** @type {Flatbuffer.GroundTruth.LaneType} */ (0);
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Lane.prototype.laneTypeLeftLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Int8Array}
 */
Flatbuffer.GroundTruth.Lane.prototype.laneTypeLeftArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? new Int8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {number} index
 * @returns {Flatbuffer.GroundTruth.LaneType}
 */
Flatbuffer.GroundTruth.Lane.prototype.laneTypeRight = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? /** @type {Flatbuffer.GroundTruth.LaneType} */ (this.bb.readInt8(this.bb.__vector(this.bb_pos + offset) + index)) : /** @type {Flatbuffer.GroundTruth.LaneType} */ (0);
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Lane.prototype.laneTypeRightLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Int8Array}
 */
Flatbuffer.GroundTruth.Lane.prototype.laneTypeRightArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? new Int8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Flatbuffer.GroundTruth.Lane.startLane = function(builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
Flatbuffer.GroundTruth.Lane.addId = function(builder, id) {
  builder.addFieldInt32(0, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} timestampOffset
 */
Flatbuffer.GroundTruth.Lane.addTimestamp = function(builder, timestampOffset) {
  builder.addFieldOffset(1, timestampOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Lane.createTimestampVector = function(builder, data) {
  builder.startVector(8, data.length, 8);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addFloat64(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Flatbuffer.GroundTruth.Lane.startTimestampVector = function(builder, numElems) {
  builder.startVector(8, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} leftOffset
 */
Flatbuffer.GroundTruth.Lane.addLeft = function(builder, leftOffset) {
  builder.addFieldOffset(2, leftOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Flatbuffer.GroundTruth.Lane.startLeftVector = function(builder, numElems) {
  builder.startVector(24, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} rightOffset
 */
Flatbuffer.GroundTruth.Lane.addRight = function(builder, rightOffset) {
  builder.addFieldOffset(3, rightOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Flatbuffer.GroundTruth.Lane.startRightVector = function(builder, numElems) {
  builder.startVector(24, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} spineOffset
 */
Flatbuffer.GroundTruth.Lane.addSpine = function(builder, spineOffset) {
  builder.addFieldOffset(4, spineOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Flatbuffer.GroundTruth.Lane.startSpineVector = function(builder, numElems) {
  builder.startVector(24, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} laneTypeLeftOffset
 */
Flatbuffer.GroundTruth.Lane.addLaneTypeLeft = function(builder, laneTypeLeftOffset) {
  builder.addFieldOffset(5, laneTypeLeftOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<Flatbuffer.GroundTruth.LaneType>} data
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Lane.createLaneTypeLeftVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Flatbuffer.GroundTruth.Lane.startLaneTypeLeftVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} laneTypeRightOffset
 */
Flatbuffer.GroundTruth.Lane.addLaneTypeRight = function(builder, laneTypeRightOffset) {
  builder.addFieldOffset(6, laneTypeRightOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<Flatbuffer.GroundTruth.LaneType>} data
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Lane.createLaneTypeRightVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Flatbuffer.GroundTruth.Lane.startLaneTypeRightVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Lane.endLane = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Flatbuffer.GroundTruth.Lanes = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Flatbuffer.GroundTruth.Lanes}
 */
Flatbuffer.GroundTruth.Lanes.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Flatbuffer.GroundTruth.Lanes=} obj
 * @returns {Flatbuffer.GroundTruth.Lanes}
 */
Flatbuffer.GroundTruth.Lanes.getRootAsLanes = function(bb, obj) {
  return (obj || new Flatbuffer.GroundTruth.Lanes).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {Flatbuffer.GroundTruth.Lane=} obj
 * @returns {Flatbuffer.GroundTruth.Lane}
 */
Flatbuffer.GroundTruth.Lanes.prototype.lanes = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Flatbuffer.GroundTruth.Lane).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.Lanes.prototype.lanesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Flatbuffer.GroundTruth.Lanes.startLanes = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} lanesOffset
 */
Flatbuffer.GroundTruth.Lanes.addLanes = function(builder, lanesOffset) {
  builder.addFieldOffset(0, lanesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Lanes.createLanesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Flatbuffer.GroundTruth.Lanes.startLanesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.Lanes.endLanes = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Flatbuffer.GroundTruth.LaneOrder = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Flatbuffer.GroundTruth.LaneOrder}
 */
Flatbuffer.GroundTruth.LaneOrder.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Flatbuffer.GroundTruth.LaneOrder=} obj
 * @returns {Flatbuffer.GroundTruth.LaneOrder}
 */
Flatbuffer.GroundTruth.LaneOrder.getRootAsLaneOrder = function(bb, obj) {
  return (obj || new Flatbuffer.GroundTruth.LaneOrder).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @returns {number}
 */
Flatbuffer.GroundTruth.LaneOrder.prototype.laneId = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb.__vector(this.bb_pos + offset) + index * 4) : 0;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.LaneOrder.prototype.laneIdLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Int32Array}
 */
Flatbuffer.GroundTruth.LaneOrder.prototype.laneIdArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? new Int32Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.LaneOrder.prototype.timestamp = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
Flatbuffer.GroundTruth.LaneOrder.prototype.mutate_timestamp = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 6);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Flatbuffer.GroundTruth.LaneOrder.startLaneOrder = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} laneIdOffset
 */
Flatbuffer.GroundTruth.LaneOrder.addLaneId = function(builder, laneIdOffset) {
  builder.addFieldOffset(0, laneIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.LaneOrder.createLaneIdVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Flatbuffer.GroundTruth.LaneOrder.startLaneIdVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} timestamp
 */
Flatbuffer.GroundTruth.LaneOrder.addTimestamp = function(builder, timestamp) {
  builder.addFieldFloat64(1, timestamp, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.LaneOrder.endLaneOrder = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Flatbuffer.GroundTruth.LaneOrders = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Flatbuffer.GroundTruth.LaneOrders}
 */
Flatbuffer.GroundTruth.LaneOrders.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Flatbuffer.GroundTruth.LaneOrders=} obj
 * @returns {Flatbuffer.GroundTruth.LaneOrders}
 */
Flatbuffer.GroundTruth.LaneOrders.getRootAsLaneOrders = function(bb, obj) {
  return (obj || new Flatbuffer.GroundTruth.LaneOrders).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {Flatbuffer.GroundTruth.LaneOrder=} obj
 * @returns {Flatbuffer.GroundTruth.LaneOrder}
 */
Flatbuffer.GroundTruth.LaneOrders.prototype.ordering = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Flatbuffer.GroundTruth.LaneOrder).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
Flatbuffer.GroundTruth.LaneOrders.prototype.orderingLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Flatbuffer.GroundTruth.LaneOrders.startLaneOrders = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} orderingOffset
 */
Flatbuffer.GroundTruth.LaneOrders.addOrdering = function(builder, orderingOffset) {
  builder.addFieldOffset(0, orderingOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.LaneOrders.createOrderingVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Flatbuffer.GroundTruth.LaneOrders.startOrderingVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Flatbuffer.GroundTruth.LaneOrders.endLaneOrders = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for ECMAScript6 Modules
export {Flatbuffer};
